package GUI;

import Controlador.Controlador;
import data.Perro;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rober y Cris
 */
public class PanelPpal extends javax.swing.JPanel {

    DefaultTableModel modelo;
    Controlador c;

    public PanelPpal(Controlador c) {
        this.c = c;
        initComponents();
        minitComponets();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        b_insertar = new javax.swing.JButton();
        b_borrar = new javax.swing.JButton();
        b_modificar = new javax.swing.JButton();
        b_buscar = new javax.swing.JButton();
        b_estadisticas = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 425));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        b_insertar.setText("Insertar Perro");
        b_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_insertarActionPerformed(evt);
            }
        });

        b_borrar.setText("Borrar Perro");
        b_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_borrarActionPerformed(evt);
            }
        });

        b_modificar.setText("Modificar Perro");
        b_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_modificarActionPerformed(evt);
            }
        });

        b_buscar.setText("Buscar Perro");
        b_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_buscarActionPerformed(evt);
            }
        });

        b_estadisticas.setText("Ver Estadísticas");
        b_estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_estadisticasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_insertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_estadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_insertar)
                        .addGap(18, 18, 18)
                        .addComponent(b_borrar)
                        .addGap(18, 18, 18)
                        .addComponent(b_modificar)
                        .addGap(18, 18, 18)
                        .addComponent(b_buscar)
                        .addGap(18, 18, 18)
                        .addComponent(b_estadisticas))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_insertarActionPerformed
        new VInsertarOMod(this,c, true, null).setVisible(true);
    }//GEN-LAST:event_b_insertarActionPerformed

    private void b_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_modificarActionPerformed
        int[] filas = tabla.getSelectedRows();

        if (filas.length > 0 && filas.length < 2) {
            try {
                Perro p = new Perro();
                
                p.setId(Integer.parseInt((String)modelo.getValueAt(filas[0], 0)));
                p.setNombre((String) modelo.getValueAt(filas[0], 1));
                p.setEdad(Integer.parseInt((String)modelo.getValueAt(filas[0], 2)));
                p.setRaza((String)modelo.getValueAt(filas[0], 3));
                
                new VInsertarOMod(this,c, false, p).setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(PanelPpal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            if (filas.length <= 0) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar una fila");
            } else if (filas.length > 1) {
                JOptionPane.showMessageDialog(this, "Solo puedes seleccionar una fila");
            }
        }

    }//GEN-LAST:event_b_modificarActionPerformed

    private void b_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_borrarActionPerformed
        int[] filas = tabla.getSelectedRows();
        if (filas.length > 0) {
            Integer[] filasOrdenadas = new Integer[filas.length];
            for (int i = 0; i < filasOrdenadas.length; i++) {
                filasOrdenadas[i] = filas[i];
            }
            Arrays.sort(filasOrdenadas, Collections.reverseOrder());
            for (int i = 0; i < filasOrdenadas.length; i++) {
                try {
                    Perro p = new Perro();
                    p.setId(Integer.parseInt((String) modelo.getValueAt(filas[i], 0)));
                    c.borrarPerro(p);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
            cargarTabla(c.listaPerros());

        } else {
                JOptionPane.showMessageDialog(this, "Debes seleccionar una fila");
        }
    }//GEN-LAST:event_b_borrarActionPerformed

    private void b_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_buscarActionPerformed
        new VBuscar(c,this).setVisible(true);
    }//GEN-LAST:event_b_buscarActionPerformed

    private void b_estadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_estadisticasActionPerformed
        new VEstadisticas(c).setVisible(true);
    }//GEN-LAST:event_b_estadisticasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_borrar;
    private javax.swing.JButton b_buscar;
    private javax.swing.JButton b_estadisticas;
    private javax.swing.JButton b_insertar;
    private javax.swing.JButton b_modificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    private void minitComponets() {
        camposDeLaTabla();
        cargarTabla(c.listaPerros());
    }

    private void camposDeLaTabla() {
        String[] campos = {"Id_Perro", "Nombre", "Edad", "Raza"};
        modelo = new DefaultTableModel(campos, 0) {
            public boolean isCellEditable(int rowIndex, int vColIndex) {
                return false;
            }
        };
        tabla.setModel(modelo);
    }
    public void cargarTabla(List<Perro> perros){
        limpiarTabla();
        for (Perro p : perros) {
            String[] fila={p.getId()+"",p.getNombre(),p.getEdad()+"",p.getRaza()};
            modelo.addRow(fila);
        }
    }
    private void limpiarTabla(){
        int filas=tabla.getRowCount();
        for (int i = filas-1; i >=0; i--) {
            modelo.removeRow(i);  
        }
    }
    public DefaultTableModel getModelo() {
        return modelo;
    }

    public JTable getTabla() {
        return tabla;
    }
    
}
