package GUI;

import Controlador.Controlador;
import data.Perro;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Rober y Cris
 */
public class VBuscar extends javax.swing.JFrame {

    Controlador c;
    PanelPpal p;

    public VBuscar(Controlador c, PanelPpal p) {
        this.c = c;
        this.p = p;
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setTitle("Ventana Buscar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bTodosLosJuegos = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        bGenero = new javax.swing.JButton();
        bNombre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        bTodosLosJuegos.setText("Ver todos los perros");
        bTodosLosJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTodosLosJuegosActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bGenero.setText("Buscar por raza");
        bGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGeneroActionPerformed(evt);
            }
        });

        bNombre.setText("Buscar por nombre");
        bNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bTodosLosJuegos, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addComponent(bGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(bCancelar))
                    .addComponent(bNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(bNombre)
                .addGap(26, 26, 26)
                .addComponent(bGenero)
                .addGap(29, 29, 29)
                .addComponent(bTodosLosJuegos)
                .addGap(47, 47, 47)
                .addComponent(bCancelar)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNombreActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Introduce el nombre del perro que deseas buscar");
        Perro pe = new Perro();
        try {
            pe.setNombre(nombre);

            List<Perro> perros = c.perrosPorNombre(pe);
            if (perros.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hemos encontrado ningun perro con ese nombre");
            } else {
                p.cargarTabla(perros);
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bNombreActionPerformed

    private void bGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGeneroActionPerformed
        String raza = JOptionPane.showInputDialog(this, "Introduce la raza que deseas buscar?");
        Perro pe=new Perro();
        try {
            pe.setRaza(raza);

            List<Perro> perros = c.perrosPorRaza(pe);
            if (perros.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hemos encontrado ningun juego con ese genero");
            } else {
                p.cargarTabla(perros);
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_bGeneroActionPerformed

    private void bTodosLosJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTodosLosJuegosActionPerformed
        p.cargarTabla(c.listaPerros());
        this.dispose();
    }//GEN-LAST:event_bTodosLosJuegosActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bGenero;
    private javax.swing.JButton bNombre;
    private javax.swing.JButton bTodosLosJuegos;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
